package comunication;

/**
 * This class represents events generated by TransportLayer.
 * @author Lorenzo Corneo
 *
 */
public class TransportLayerEvent {
	private short push_value;
	
	/**
	 * Constructor that generates event.
	 * @param value New value read from Push Comunicator.
	 */
	public TransportLayerEvent(short value) {
		this.push_value = value;
	}
	
	/**
	 * Reads new value.
	 * @return Value contained inside push notification.
	 */
	public short readPushValue() {
		return this.push_value;
	}
}
